version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: CoQx6e4%EDP3XWV%9n7V
      MYSQL_DATABASE: imaginarium
      MYSQL_USER: imaginarium
      MYSQL_PASSWORD: dw3mw87t
    ports:
      - "6033:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - imaginarium
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - imaginarium
  web:
    container_name: nextjs_container
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 6033
      MYSQL_USER: root
      MYSQL_PASSWORD: CoQx6e4%EDP3XWV%9n7V
      MYSQL_DB: imaginarium
      DATABASE_URL: mysql://root:CoQx6e4%EDP3XWV%9n7V@db:3306/imaginarium
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - imaginarium

networks:
  imaginarium:
    driver: bridge
    
