FROM node:20

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/
COPY .env ./

# RUN mkdir -p .next
# RUN mkdir -p node_modules
# RUN chown node:node . node_modules .next
# RUN chown -R node:node node_modules/

RUN npm install
RUN npm prisma generate


EXPOSE 3000

# Générez le code Prisma
# RUN npm prisma generate

# Exécutez les migrations Prisma (ajustez selon votre configuration)
# RUN npm prisma migrate dev
CMD npm run build && npm run start
