version: "3.8"

services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: imaginarium
      POSTGRES_PASSWORD: dw3mw87t
      POSTGRES_DB: imaginarium
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - imaginarium
  web:
    container_name: nextjs_container
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: imaginarium
      POSTGRES_PASSWORD: dw3mw87t
      POSTGRES_DB: imaginarium
      DATABASE_URL: postgresql://imaginarium:dw3mw87t@db:5432/imaginarium
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - imaginarium

networks:
  imaginarium:
    driver: bridge
    
